# Generated by Django 5.2.17 on 2026-09-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_seed_fordspy_frontend_serviceclient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="event",
            field=models.CharField(
                choices=[
                    ("LOGIN_OK", "Login successful"),
                    ("LOGIN_FAIL", "Login failed"),
                    ("LOGIN_THROTTLED", "Login blocked by rate limit"),
                    ("LOGOUT", "Logout"),
                    ("REFRESH_OK", "Token refresh successful"),
                    ("REFRESH_FAIL", "Token refresh failed"),
                ],
                max_length=20,
            ),
        ),
    ]
