line-length = 100
target-version = "py312"

[lint]
select = ["E", "F", "I", "B", "UP", "SIM", "S", "DJ"]
ignore = ["S101"]  # asserts in tests are fine

[lint.per-file-ignores]
"*/migrations/*.py" = ["E501"]
"tests/**/*.py" = ["S105", "S106"]
"tests/factories.py" = ["N805"]

[format]
quote-style = "double"
indent-style = "space"
