# Generated by Django 5.1.15 on 2026-05-23 04:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InsightsUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True, unique=True)),
                ("count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "intelligence_insights_usage",
            },
        ),
    ]
